# Generated by Django 4.2.6 on 2023-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkassignment', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assignments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
