# Generated by Django 4.2.6 on 2023-10-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkassignment', '0004_aassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aassignment',
        ),
    ]
