# Generated by Django 4.2.6 on 2023-10-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkassignment', '0006_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='student',
            new_name='user',
        ),
    ]
