# Generated by Django 4.2.6 on 2023-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkassignment', '0008_alter_student_student_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
